## 异常处理：

**将目标代码块选中 ---> 快捷键 --> ctrl + alt + t ---> 选中 try - catch**

---

异常：在程序执行中发生的不正常情况称为 ”异常“。

### **两大类**

1.错误：JAVA虚拟机无法解决的严重问题

2.Exception：其他因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性代码进行处理.
两大类：
运行时异常【程序运行时，发生的一长串】
编译时异常【编程时，编译器检查出的异常】



### 常见的运行时异常：

1.空指针异常：	当应用程序试图在需要对象的地方使用null时，抛出该异常

2.ArithmeticException数学运算异常:	当出现异常的运算条件时，抛出此异常。

3.ArrayIndexOutOfBoundsException：	数组下标越界异常,用非法索引访问数组时抛出的异常

4.ClassCastException类型转换异常：	试图将对象强制转换为不是实例的子类时，抛出该异常。

5.NumberFormatException数字格式不正确异常：	当应用程序试图将字符串转换成一种数值类型，但该字符串不能转换为适当格式时，抛出异常。



### 编译异常：

是指在编译期间就必须处理的异常，否则代码不能通过编译。

---

### 异常处理方式：

1.try-catch-finally
程序员在代码中捕获发生的异常，自行处理

基本语法：

```java
try{
	//可以代码
	//将异常生成对应的异常对象，传递给catch块
}catch(异常) {
	//对异常的处理
}
//如果没有finally,语法是可以通过的
```

1.如果异常发生了，则异常后面的代码不会执行，直接会进入到catch块

2.如果异常没有发生，则顺序执行try代码块，不会进入到catch

3.如果希望不管是否发生异常，都执行某段代码（比如关闭连接，释放资源等）
则使用如下代码		finally{ }

4.可以进行 try-finally 配合使用，相当于没有捕获异常，不管有没有发生异常，都必须执行业务逻辑



## 2.throws

将发生的异常抛出，交给调用者来处理，用最顶级的处理者JVM

在方法声明中用throws语句可以**声明抛出异常的列表**（可以抛出多个异常），throws后面的异常类型可以是**方法中产生的异常类型**，也可以是**它的父类**。

细节：
1.对于编译异常，程序中必须处理
2.对于运行异常，程序中如果没有处理，默认就是throws的方法处理
3.子类重写父类的方法时，对抛出异常的规定：子类重写父类的方法，**所抛出的异常类型要么和父类抛出的异常一致，要么为父类抛出异常的类型的子类型**
4.在throws过程中，如果有方法try-catch，就相当于处理异常，就可以不必throws

如果抛出的是运行异常，在调用抛出异常的方法的地方并不要求程序员显示处理，因为有默认处理机制。

---



## 自定义异常

步骤：
1.定义类：	自定义异常类名（程序员自己写） 继承Exception 或 RuntimeException
2.如果基础Exception,属于编译异常
3.如果继承RuntimeException，属于运行异常

一般情况下，我们自定义异常继承 RuntimeException
即把自定义异常 做成 运行时异常， 好处是， 我们可以使用默认的处理机制

---

## Throws 和 throw 的区别

### 					         **意义										位置											后面跟的东西**

throws：异常处理的一种方式                   方法声明处							异常类型

throw:    手动生成异常对象的关键字		 方法体中								异常对象

---

### **练习：**

1.编写一个程序，接收命令行的两个参数（整数），计算两数相除。

2.计算两个数相除，要求使用方法  **cal ( int n1,  int n2 )**

3.对数据格式不正确，缺少命令行参数，除0进行异常处理

```java
public class Homework01 {
    public static void main(String[] args) {
        //先验证输入的参数的个数是否正确
        try {
            if (args.length != 2) {
                throw new ArrayIndexOutOfBoundsException("参数个数不对");
            }
            int n1 = Integer.parseInt(args[0]);
            int n2 = Integer.parseInt(args[1]);

            double res = cal(n1, n2);
            System.out.println("计算结果是=" + res);
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println(e.getMessage());
        } catch (NumberFormatException e) {
            System.out.println("参数格式不正确，需要输出整数");
        } catch (ArithmeticException e) {
            System.out.println("出现除0的异常");
        }
    }

    public static double cal(int n1, int n2) {
        return n1 / n2;
    }
}
```

